### ISSUE TITLE
Plugin seems to be working but editor doesn't pop up

### ISSUE THREAD

**Issue by chrostino** [sethyuan/logseq-plugin-math-editor#1]
as from the screenshot below, the plugin seems to be active and working, showing the edit button
![image](https://github.com/sethyuan/logseq-plugin-math-editor/assets/100096435/78641167-13ee-43eb-8042-0e9412ecaf81)

but when I click it, it just lets me edit text, and the math editor doesn't appear
![image](https://github.com/sethyuan/logseq-plugin-math-editor/assets/100096435/75142339-dbe5-4a0a-b44c-2c42a2d136bf)

**Comment by sethyuan** [comment]
Fixed, please check the new version.

**Comment by chrostino** [comment]
works now :+1: :+1: 
this was very fast ty

**Comment by chrostino** [comment]
little update,
now the plugin works really well for equations in their own line, like these
![image](https://github.com/sethyuan/logseq-plugin-math-editor/assets/100096435/8618eb39-e494-4cd2-8710-2ca3de89a1a4)

but doesn't work for inline equations like this
![image](https://github.com/sethyuan/logseq-plugin-math-editor/assets/100096435/4ecab2ce-6014-406c-a6ea-7eb41d6928dd)

**Comment by sethyuan** [comment]
Strange, I did test the inline case. Let me look into it again.

**Comment by chrostino** [comment]
sorry, I don't know if I may be dong somenthing wrong

**Comment by sethyuan** [comment]
Updated a new version, it should have it fixed. Can you help try it?

**Comment by chrostino** [comment]
perfect, everything works. very nice
